name: Top20 Automation

on:
  push:
  schedule:
    - cron: "0 6 * * 1"

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node Modules
        run: |
          git submodule init
          npm install
      - name: Run Linter
        run: |
          npm run lint
      - name: Sec Test
        run: |
          npm audit --audit-level=moderate
      - name: Unit Tests and Coverage
        run: |
          npm run coverage
      - name: Report Job Status
        if: ${{ failure() }}
        run: |
          if [[ $status == "Failure" ]]; then curl -X POST -H 'Content-type: application/json' --data '{"text":"Top20 Backend: build has failed!"}' "${WEBHOOK_URL}"; fi
        env:
          status: ${{job.status}}
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
