name: Top20 Automation

on:
  push:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node Modules
        run: |
          git submodule init
          npm install
      - name: Run Linter
        run: |
          npm run lint
      - name: Sec Test
        run: |
          npm audit --production
      - name: Unit Tests and Coverage
        run: |
          npm run coverage
      - name: Report Job Status
        if: ${{ failure() }}
        run: |
          if [[ $status == "Failure" ]]; then curl -X POST -H 'Content-type: application/json' --data '{"text":"Top20 Backend: build has failed!"}' "${WEBHOOK_URL}"; fi
        env:
          status: ${{job.status}}
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Stage -- Prepare for Deploy
        if: ${{ github.ref == 'refs/heads/develop' && github.event_name == 'push' }}
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          version: "302.0.0"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Stage -- Automated Deploy
        if: ${{ github.ref == 'refs/heads/develop' && github.event_name == 'push' }}
        run: |
          echo -n "${STAGE_ENV}" | base64 --decode > .env.yaml
          echo "Deploying ..."
          gcloud functions deploy top-20-backend-stage --entry-point lastfm --runtime nodejs10 --trigger-http --env-vars-file=.env.yaml --source=. --allow-unauthenticated 2>&1 > /dev/null
        env:
          STAGE_ENV: ${{ secrets.STAGE_ENV }}
      - name: Stage -- Report Success
        if: ${{ github.ref == 'refs/heads/develop' && github.event_name == 'push' }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Top20 Backend: automated deploy of develop branch successful!"}' "${WEBHOOK_URL}"
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      - name: Stage -- Report Failure
        if: ${{ failure() }}
        run: |
          [[ ${REF} == 'refs/heads/develop' ]] && [[ ${EVENT} == 'push' ]] && curl -X POST -H 'Content-type: application/json' --data '{"text":"Top20 Backend: automated deploy of develop branch failed!"}' "${WEBHOOK_URL}"
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          REF: ${{ github.ref }}
          EVENT: ${{ github.event_name }}

      - name: Production -- Prepare Release Content
        if: contains(github.ref, '/tags/v')
        run: |
          NEWTAG=${GITHUB_REF#refs/tags/}
          echo "NEWTAG=${NEWTAG}" >> $GITHUB_ENV
      - name: Production -- Generate Changelog
        if: contains(github.ref, '/tags/v')
        uses: scottbrenner/generate-changelog-action@v1.3.3
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Production -- Create Release
        if: contains(github.ref, '/tags/v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEWTAG }}
          release_name: Release ${{ env.NEWTAG }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: true
          prerelease: false

      - name: Production -- Checkout Master Branch
        if: contains(github.ref, '/tags/v')
        run: |
          git checkout origin/master
      - name: Production -- Report Success
        if: contains(github.ref, '/tags/v')
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Top20 Backend: automated release has been created for ${TAG}: https://github.com/playcounts/top20-backend/releases\"}" "${WEBHOOK_URL}"
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          TAG: ${{ env.NEWTAG }}
      - name: Production -- Report Failure
        if: failure() && contains(github.ref, '/tags/v')
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Top20 Backend: automated production release has failed!"}' "${WEBHOOK_URL}"
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
